// Generated by CoffeeScript 1.4.0
(function() {

  $(document).ready(function() {
    var init, onResize, reposition, wizardry;
    init = function() {
      var viewportHeight, viewportWidth;
      viewportWidth = $(window).width();
      viewportHeight = $(window).height();
      $('.right, .left').css('height', viewportHeight);
      return $('.right .inside').css('height', viewportHeight - 100);
    };
    reposition = function(img, width, height) {
      var leftOffset, topOffset, viewportHeight, viewportWidth;
      viewportWidth = $(window).width();
      viewportHeight = $(window).height();
      $('.right, .left').css('height', viewportHeight);
      $('.right .inside').css('height', viewportHeight - 100);
      topOffset = ((viewportHeight - height) / 2) - 35;
      leftOffset = (((viewportWidth / 2) - width) / 2) - 12;
      $('.top').css({
        top: topOffset,
        left: leftOffset
      });
      $('.top').css({
        width: width,
        height: height
      });
      $('.hhhhold-up').css({
        width: width,
        height: height
      });
      return $('.top h1').css({
        width: width,
        lineHeight: height + 'px',
        fontSize: width / 6 + 'px'
      });
    };
    onResize = function() {
      var img;
      img = $('.hhhhold-up img');
      return reposition(img, img.width(), img.height());
    };
    wizardry = function(width, height, params) {
      var framePadding, img, maxImgHeight, maxImgWidth, minImgHeight, minImgWidth, url, viewportHeight, viewportWidth;
      viewportWidth = $(window).width();
      viewportHeight = $(window).height();
      if (viewportWidth < 500) {
        framePadding = 20;
      } else {
        framePadding = 150;
      }
      minImgWidth = (viewportWidth / 2) - framePadding * 2;
      maxImgWidth = (viewportWidth / 2) - framePadding;
      minImgHeight = viewportHeight / 3;
      maxImgHeight = viewportHeight - framePadding;
      if (width == null) {
        width = Math.floor(Math.random() * (maxImgWidth - minImgWidth + 1) + minImgWidth);
      }
      if (height == null) {
        height = Math.floor(Math.random() * (maxImgHeight - minImgHeight + 1) + minImgHeight);
      }
      img = new Image();
      if (!params) {
        img.src = "https://hhhhold.com/" + width + "x" + height + "?homepage=true";
        url = "hhhhold.com/" + width + "x" + height;
      } else {
        img.src = "https://hhhhold.com/" + params + "?homepage=true";
        url = "hhhold.com/" + params;
      }
      $('.hhhhold-up img').fadeOut('slow', function() {
        return $(this).remove();
      });
      return $(img).load(function() {
        if ($('.hhhhold-up img').length < 1) {
          reposition(img, img.width, img.height);
          $('.caption').text(url);
          return $(img).hide().appendTo('.hhhhold-up').delay(300).fadeIn('slow');
        }
      });
    };
    init();
    wizardry();
    $('.top').on('click', function() {
      return wizardry();
    });
    $(window).on('resize', function() {
      return onResize();
    });
    return $('li[data-params], span[data-params]').on('click', function() {
      var height, params, width;
      return wizardry(width = null, height = null, params = $(this).data('params'));
    });
  });

}).call(this);
